---
title: "Grading rubric"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

[**Grading Rubric (10 pts max)**]{.underline}**:**

Assignments will be graded using the rubric below.

-   **Answers**: 4 pts 

-   **Demonstrating process**: 3 pts

-   **Providing context and relevance**: 3 pts

+-------------------------------------+----------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
|                                     | **4 points**                                 | **3 points**                                                                                                                                                                                                                                                                                                   | **2 points**                                                                                                                                                   | **1 point**                                                                                                             | **0 points**                                                                              |
+-------------------------------------+----------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| **Answers**                         | Answers are correct at least 90% of the time | Answers are usually correct (75-90%)                                                                                                                                                                                                                                                                           | Answers are sometimes correct (50-74%)                                                                                                                         | Answers are generally incorrect (\<50%)                                                                                 | Answers are incorrect and no work was shown (demonstrating process has 0 pts)             |
|                                     |                                              |                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                |                                                                                                                         |                                                                                           |
| **(4 pts max)**                     |                                              |                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                |                                                                                                                         |                                                                                           |
+-------------------------------------+----------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| **Demonstrating process**           |                                              | All relevant work is shown, including all steps for figuring out answers.                                                                                                                                                                                                                                      | Relevant work and steps for figuring out answers are generally provided but incomplete.                                                                        | Relevant work and steps for figuring out answers are generally missing.                                                 | No relevant work is shown, including steps for figuring out answers.                      |
|                                     |                                              |                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                |                                                                                                                         |                                                                                           |
| **(3 pts max)**                     |                                              | R code and output are provided for every question for which R was used.                                                                                                                                                                                                                                        | R code and output are generally provided but incomplete for questions that use R.                                                                              | R code and output are generally missing for questions that use R.                                                       | R code and output are not provided for questions for which R was used.                    |
+-------------------------------------+----------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| **Providing context and relevance** |                                              | Answers are given in complete sentences with all relevant information for the question as appropriate (context of research question, units, descriptive statistics, explanation of what data visualization is showing, confidence intervals, p-values, test- statistics, etc.), and interpretation of results. | Answers are given in complete sentences. Some relevant information may be provided, but much is missing. Context of research question only sometimes provided. | Answers are rarely given in complete sentences. Relevant information is not provided. Little to no context is provided. | Answers are not in complete sentences. Relevant information and context are not provided. |
|                                     |                                              |                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                |                                                                                                                         |                                                                                           |
| **(3 pts max)**                     |                                              |                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                |                                                                                                                         |                                                                                           |
+-------------------------------------+----------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+

: {.striped .hover tbl-colwidths="\[5, 25, 25, 25, 25, 25\]"}
