---
title: "UNDER CONSTRUCTION: Schedule"
date: "9/30/24"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    # toc: true
editor_options: 
  chunk_output_type: console
---

| Week                    |  Dates  |Day    | Topics                                                                                           | Chapter sections                       |
|:-----------------------:|:-------:|:-----:|:-------------------------------------------------------------------------------------------------|:---------------------------------------|
|  [1](weeks/week_01.qmd) | M 9/30  |       | No class: <br> OHSU New Student Orientation                                                      |                                        |
|                         | W 10/2  | **1** | Introduction to R & RStudio                                                                      |                                        |
|  [2](weeks/week_02.qmd) | M 10/7  | **2** | Intro to Data, Data collection                                                                   | 1.1-1.3                                |
|                         | W 10/9  | **3** | Summarizing numerical data, <br> Probability                                                     | 1.4, 2.1-2.2.4                         |
|                         | Sa 10/12|       | [HW 1 Due](homework/HW_1_F24_bsta511.qmd) (Days 1 - 3)                                           |                                        |
|  [3](weeks/week_03.qmd) | M 10/14 | **4** | Bayes' Theorem, R Packages                                                                       | 2.2.5, extra                           |
|                         | W 10/16 | **5** | Data visualization, <br> exploratory data analysis (EDA), <br> and summarizing categorical data  | 1.5-1.7, extra                         |
|                         | Sa 10/19|       | [HW 2 Due](homework/HW_2_F24_bsta511.qmd) (Days 4 - 5)                                           |                                        |
|  [4](weeks/week_04.qmd) | M 10/21 | **6** | Random variables, <br> Binomial distribution                                                     | 3.1-3.2                                |
|                         | W 10/23 | **7** | Normal and Poisson distributions                                                                 | 3.3-3.4                                |
|                         | Sa 10/26|       | [HW 3 Due](homework/HW_3_F24_bsta511.qmd) (Days 6 - 7)                                           |                                        |
|  [5](weeks/week_05.qmd) | M 10/28 | **8** | Variability in estimates                                                                         | 4.1                                    |
|                         | W 10/30 |       | **[Exam 1: Days 1-7](weeks/week_05.qmd#sec-Exam1info)**                                          | **Ch 1, 2, 3.1-3.4**                   |
|  [6](weeks/week_06.qmd) | M 11/4  | **9** | Confidence Intervals                                                                             | 4.2                                    |
|                         | W 11/6  | **10**| Hypothesis Testing: <br> Single-sample with *t*-distribution <br> & Two-sample paired data       | 4.3, 5.1, 5.2                          |
|                         | Sa 11/9 |       | [HW 4 Due](homework/HW_4_F24_bsta511.qmd) (Days 8 - 10)                                          |                                        |
|  [7](weeks/week_07.qmd) | M 11/11 | **11**| Hypothesis Testing: <br> Two-sample independent data; <br> Power                                 | 5.3-5.4, extra                         |
|                         | W 11/13 | **12**| Inference for a single proportion <br> or difference in proportions                              | 8.1-8.2                                |
|                         | Sa 11/16|       | [HW 5 Due](homework/HW_5_F24_bsta511.qmd) (Days 11 - 12)                                         |                                        |
|  [8](weeks/week_08.qmd) | M 11/18 | **13**| Chi-squared tests, <br> Fishers exact test                                                       | 8.3-8.4                                |
|                         | W 11/20 | **14**| Comparing Means with ANOVA.                                                                      | 5.5, extra                             |
|                         | Sa 11/23|       | [HW 6 Due](homework/HW_6_F24_bsta511.qmd) (Days 13 - 14)                                         |                                        |
|  [9](weeks/week_09.qmd) | M 11/25 |       | **[Exam 2: Days 8-13](weeks/week_08.qmd#sec-Exam2info)**                                         | **Ch 4, 5.1-5.4; <br> extra, 8.1-8.4** |
|                         | W 11/27 | **15**| Simple Linear Regression                                                                         | 6.1-6.2                                |
|  [10](weeks/week_10.qmd)| M 12/2  | **16**| Simple Linear Regression                                                                         | 6.3-6.4                                |
|                         | W 12/4  | **17**| Non-parametric tests <br> (sign, signed-rank, rank-sum, <br> Kruskal-Wallis)                     | Extra                                  |
|                         | Sa 12/7 |       | [HW 7 Due](homework/HW_7_F24_bsta511.qmd) (Days 15 - 17)                                         |                                        |
|  [11](weeks/week_11.qmd)| M 12/9  |       | Review - catch up                                                                                |                                        |
|                         | W 12/11 |       | **[Exam 3 due (take home)](weeks/week_11.qmd#sec-exam-3---final-version-posted): <br> Cumulative with a focus on Days 14-17**                           | **Ch 5.5, 6, <br> non-parametric**     |
