---
title: "Draft HW 4: BSTA 511/611 F25"
pagetitle: "HW 4"
author: "Your name here - update this!!!!"
date: "Due 11/15/25"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: false
    number-depth: 4
    theme: lumen
    self-contained: true
    html-math-method: mathjax
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE, fig.height = 2, fig.width = 4)
```

**Due 11/15/25**

Download the .qmd file for this assignment from <https://github.com/niederhausen/BSTA_511_F25/blob/main/homework/HW_4_DRAFT_F25_bsta511.qmd>


## [DRAFT]{style="color:darkorange"}

*[I still need to add questions for Days 11-12 material.]{style="color:darkorange"}*  




## Graded exercises

The exercises listed below will be graded for this assignment. You are **strongly** encouraged to complete the entire assignment. You will receive feedback on exercises you turn in that are not being graded.

-   **Book exercises**
    -   5.22 
-   **Non-book exercise**
    -   tbd
-   **R exercises**
    -   R1: Swim times


## Directions


-   Please upload your homework to [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F25/tool/094ccc0a-8f85-4069-af5b-e035ef8b79e2). **Upload both your .qmd code file and the rendered .html file** (or just your pdf if completing the assignment by hand).
    -   Use the assignment .qmd file linked to above as a template for your own assignment.
-   Please always use the following naming convention for submitting your files:
    -   **Lastname_Firstname_HWx.qmd**, such as Niederhausen_Meike_HW2.qmd
    -   **Lastname_Firstname_HWx.html**, such as Niederhausen_Meike_HW2.html
-   For each question, make sure to **show all of your work**.
    -   This includes all code and resulting output in the html file to support your answers for exercises requiring work done in R (including any arithmetic calculations).
    -   For non-calculation questions, this includes an explanation of your answer (*why did you choose your answer?*).
-   For each question, include a **sentence summarizing the answer** for that question in the context of the research question.

::: callout-tip
It is a good idea to try rendering your document from time to time as you go along! Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::

# Book exercises



## 5.16 Paired or not, Part II 



## 5.22 DDT exposure 


# R exercises 

## Load packages

Load all the packages you need in the first code chunk of the file that starts with `#| label: "setup"`.



## R1: Swim times

* In these exercises you will use R to work through the swim times example from Section 5.2 in the textbook. 
* The data are in the `oibiostats` package and called `swim`.


### (a) Mean & SD of differences 

__Calculate the mean and standard deviation for the differences in swim times, and compare them to the ones in the book. Which order were the differences calculated, wet suit - swim suit or the opposite? Were all the differences positive?__ 


### (b) Dot plot of differences

__Create a dot plot of the differences in swim times and comment on the distribution shape.__ 


### (c) Hypothesis test

__Run the appropriate statistical test in R as both a one-sample t-test and a paired t-test to verify the test statistic, p-value, and CI in the text. Use inline R code to pull these values from the test output when writing up your comparison of these values to the book's values.__ 

