---
title: "UNDER CONSTRUCTION: Week 10"
description: "Simple Linear Regression (cont'd) and Nonparametric Tests"
date: "12/2/2024"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Overview of Week 10

::::: grid
::: g-col-6
### Mon: Day 16

-   Simple Linear Regression Part 2
-   Sections 6.3-6.4
:::

::: g-col-6
### Wed: Day 17

-   Nonparametric tests
-   This material is not in our textbook. Please see Chapter 13: Nonparametric tests of Pagano’s *Principles of Biostatistics*, 2022 edition as a supplementary resource.
    -   This chapter can be downloaded from the OHSU library’s eBook at https://ebookcentral.proquest.com/lib/ohsu/detail.action?docID=6950388&pq-origsite=primo
:::
:::::

## Slides & Recordings

-   **Pre-recorded** lessons are on [Echo Video](https://echo360.org/section/af47457c-bed2-48d7-84ae-eaa2d44f9add/home).

| Day | Topic | Slides: html | Slides: pdf | Slides: web-page | Slides with notes | Recording Link | Duration | Code: qmd | Code: html |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| 16 | Simple Linear Regression cont'd: 6.3-6.4 | [Day 16](../slides/Day16_bsta511.qmd) | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day16_bsta511.pdf) | [{{< iconify streamline web size=20px >}}](../slides_md/Day16_bsta511_md.qmd) |  | [Day 16](https://echo360.org/lesson/27f794ca-3c07-46ef-8bd1-76c4ef035f28/classroom#sortDirection=desc) \* | 1 hr 26 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day16_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day16_bsta511_code.qmd) |
| 17 | Sign test & Sign-rank test: Slides 1-31 |  | [{{< iconify bi file-earmark-pdf-fill size=20px >}}](../slides_pdf/Day17_bsta511.pdf) |  | [{{< iconify pepicons-pop pen-circle-filled size=20px >}}](../slides_notes/Day17_bsta511_notes.pdf) | [Day 17 Part 1](https://echo360.org/lesson/768baa9b-1d17-45c0-812d-4cf7e4ffc2b4/classroom#sortDirection=desc) | 56 min | [{{< iconify simple-icons:quarto >}}](https://github.com/niederhausen/BSTA_511_F24/blob/main/slides_code/Day17_bsta511_code.qmd) | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day17_bsta511_code.qmd) |
|  | Wilcoxon rank-sum test, Kruskal-Wallis test: Slides 32-53 |  | same |  | same | [Day 17 Part 2](https://echo360.org/lesson/8cff92b0-504e-4360-8a7a-45aef5cbee09/classroom#sortDirection=desc) | 41 min | same | [{{< iconify ph file-html-light size=25px >}}](../slides_code/Day17_bsta511_code.qmd#wilcoxon-rank-sum-test-1) |

: {.striped .hover tbl-colwidths="\[3, 10, 8, 5, 5, 5, 6, 6, 5, 5\]"}

*`*`Edited live recording from F23 class*

## Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F24/tree/main/data)

-   Day 16: [lifeexp_femlit_water_2011.csv](/data/lifeexp_femlit_water_2011.csv)

## Class discussion

During class you will be working in groups discussing the following:

### Day 16

-   Questions from HW 7
    -   Book
        -   Warm-up: 6.12
        -   6.28, 6.32
    -   R2 (a) - (j): Life expectancy vs. CO~2~ emissions

### Day 17

-   Questions from HW 7
    -   Nonparametric Tests: NPT 1-3

## Homework

-   [HW 7](../homework/HW_7_F24_bsta511.qmd) covers Days 15 -17 and is due on Sat, 12/7
-   Check out this [spreadsheet](https://docs.google.com/spreadsheets/d/1k_NivXZftdlRgRyTT3fUZCndW4eoXCzAs-DEIml6K3Y/edit?gid=0#gid=0) for typos in book.
